name: Mac Release
run-name: ${{ github.actor }} is building a Mac release

on:
  push:
    branches: ["latest"]

  workflow_dispatch:

permissions:
  contents: write 

jobs:
  deploy-on-mac:
    runs-on: macos-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: c4-foundations
          environment-file: environment.yml
          auto-activate-base: false
          
      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build and deploy on Mac
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          teamId: ${{ secrets.APPLE_TEAM_ID }}
          appleId: ${{ secrets.APPLE_ID }}
          appleIdPassword: ${{ secrets.APPLE_PASSWORD }}
        run: npm run build -- --target desktop --publish
